### ISSUE TITLE
Prerendering

### ISSUE THREAD

**Issue by hampelm** [detroitledger/detroitledger#46]
It'd be nicer to have URLs like `/#/organization/detroit-ledger`, with a slug in the URL. It'd probably also help SEO. How should we implement that? 

- Is there a slug field in the backend that's not currently being returned by the API? 
- Can we set up a filter for exact slugs (eg 404s when a slug filter is not found instead of fuzzy matching)

(this ticket might be better off in the API)

**Comment by bnchdrff** [comment]
for now, we'll use prerender.io to prerender backbone views

in the future we will make the javascript work serverside: #42

**Comment by bnchdrff** [comment]
@hampelm prerendering doesn't seem to work -- http://localhost:3334/?_escaped_fragment_=/about-detroit-ledger doesn't render as http://localhost:3334/#!/about-detroit-ledger

also i defined a dockerfile for the frontend (pushed to the mh-phantom branch) and have a nginx proxy ready to go!

**Comment by bnchdrff** [comment]
ugh, nevermind -- the prerender docker container i'm using had basicAuth enabled!

**Comment by bnchdrff** [comment]
Got prerender docker container linkages working locally... will work on the nginx reverse proxy tomorrow & hopefully launch!

fork of that other prerender dockerfile here: https://github.com/bnchdrff/dockerfiles/tree/master/prerender

**Comment by bnchdrff** [comment]
w00 launched

**Comment by bnchdrff** [comment]
ugh almost... 301 redirects from the https reverse proxy. this will take a bit more thinking

**Comment by bnchdrff** [comment]
fixed with a change to server.js... everything is running smoothly but damn, prerender eats up the ram!!! we might need to beef up our server.
