### ISSUE TITLE
Pages need good titles

### ISSUE THREAD

**Issue by hampelm** [detroitledger/detroitledger#56]
Google is starting to try its own 😬

![screen shot 2015-01-11 at 5 50 42 pm](https://cloud.githubusercontent.com/assets/86435/5697297/70faacb2-99ba-11e4-8008-f043f7776514.png)

**Comment by bnchdrff** [comment]
my PR is somewhat dirty style but this'll get us by for the time being.

it'd be nice to have the complete HTML output from our app served via our templating system & use partials for each page region so we can muss with anything we want.

**Comment by bnchdrff** [comment]
pushed to live
