### ISSUE TITLE
"given" ambiguity

### ISSUE THREAD

**Issue by bnchdrff** [detroitledger/detroitledger#62]
the language we use is a bit vague in my opinion... i intitally read it is "organization was given this amount of money" rather than "organization has given out this amount of money" -- other phrasing ideas?

**Comment by bnchdrff** [comment]
![screenshot from 2015-01-15 12 14 58](https://cloud.githubusercontent.com/assets/99194/5762488/583e4924-9cb0-11e4-956d-d707ecb251be.png)

**Comment by hampelm** [comment]
"Gave"?

**Comment by bnchdrff** [comment]
Yeah, "Gave".

Big decisions being made over here, eh?!?! :hammer:
