### ISSUE TITLE
A couple crawl errors

### ISSUE THREAD

**Issue by hampelm** [detroitledger/detroitledger#63]
Still had this in my clipboard from early this morning. Webmaster tools reported a couple crawl errors, mostly 504s, one 502. I can't reproduce; maybe memory-related? 

```
?_escaped_fragment_=/grants/1201
502
1/10/15

?_escaped_fragment_=/grants/4071
504
1/13/15

?_escaped_fragment_=/organizations/420
504
1/14/15

?_escaped_fragment_=/organizations/251
504
1/14/15

?_escaped_fragment_=/organizations/2775
504
1/14/15

?_escaped_fragment_=/organizations/4203
504
1/14/15

?_escaped_fragment_=/organizations/479
504
1/14/15
```

**Comment by bnchdrff** [comment]
Yup, looks like weo OOMed... crap.
-- 
Benjamin Chodoroff
tel:3139992892
https://detriot.org

**Comment by bnchdrff** [comment]
I'm setting up a cronjob to restart the prerender container every 3 hours...

**Comment by bnchdrff** [comment]
added `* 0-23/3 * * * /usr/bin/docker restart b1c720aff401` to our crontab. :pig: :tractor: so dirty :-1:

**Comment by hampelm** [comment]
Thanks!! It's paying off! 
![screen shot 2015-01-16 at 6 33 45 pm](https://cloud.githubusercontent.com/assets/86435/5786133/416612aa-9dae-11e4-94e8-50b3c20b83a6.png)

**Comment by hampelm** [comment]
Still getting a couple errors every day. I'll close this for now and will keep an eye on it; think we've done what we can.
