### ISSUE TITLE
Google gets confused about some page titles 

### ISSUE THREAD

**Issue by hampelm** [detroitledger/detroitledger#64]
One page has the grant total as its title:

![screen shot 2015-01-16 at 2 15 23 pm](https://cloud.githubusercontent.com/assets/86435/5782551/2468d1ac-9d8a-11e4-8113-813ff67d0c54.png)

I bet this comes from before our title update (#56). We should keep an eye out, though. And possibly change the HTML of the grant pages so the headers are a bit more google-friendly (right now, total, recipient, and funder are all h2s)

**Comment by bnchdrff** [comment]
`<dl><dd><dt>` would lend itself well to the stats...

w.r.t. the botched titles, i think it's a google cache issue... see https://www.detroitledger.org/?_escaped_fragment_=/grants/682 -- our server outputs the correct title.

speaking of all this, we should impelment hgrant microformat!

**Comment by hampelm** [comment]
Looks like this is clearing up.
